// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wqvjjltdtpixcebqvsbf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndxdmpqbHRkdHBpeGNlYnF2c2JmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NTUxMzUsImV4cCI6MjA2NTAzMTEzNX0.0XeV9iUci6OlJr64EV7VBFAXnBPdijKjSokCPp5_cQQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);